export {Login} from './Login'
export {Register} from './Register'
export {ForgotPassword} from './ForgotPassword'
export {ResetPassword} from './ResetPassword'
export {Home} from './Home'
export {LandingPage} from './LandingPage'

export {Cuisines} from './Cuisines'
export {CuisineDetail} from './CuisineDetail'
export {Reservation} from './Reservation'
export {ViewReservations} from './ViewReservations'
export {AddMenu} from './AddMenu'
export {AddReview} from './AddReview'
export {Account as UserProfile} from './Profile'
export {ChangePassword} from './ChangePassword'
export {MapUser} from './Map'
export {Reccomendations} from './Reccomendations'
export {ViewCuisineMap} from './ViewCuisineMap'

export {GeneralForums} from './GeneralForums'


export {CuisineHome} from './cuisine/CuisineHome'
export {NewCuisine} from './cuisine/NewCuisine'
export {CuisineMenu} from './cuisine/CuisineMenu'
export {CuisineOwnerMenuAdd} from './cuisine/CusisineOwnerMenuAdd'
export {CuisineAnalytics} from './cuisine/CuisineAnalytics'
export {ReservationsPage} from './cuisine/ReservationsPage'
export {Map} from './cuisine/Map'
export {PageNotFound} from './cuisine/404Page'
export {Account} from './cuisine/Account'